### NumPy Indexing and Selection

In [2]:
import numpy as np

In [3]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [8]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [12]:
arr[0:5] = 100          # broadcasting the values in the original array

In [10]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [11]:
arr = np.arange(0, 11)

In [13]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [14]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [18]:
arr_2d[1, 2]

30

In [20]:
arr_2d[1:, 1:]

array([[25, 30],
       [40, 45]])

In [21]:
arr = np.arange(1, 11)

In [22]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
bool_arr = arr > 5

In [27]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [28]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])