In [3]:
my_list = [1, 2, 3]

In [4]:
import numpy as np

In [6]:
arr = np.array(my_list)

In [7]:
arr

array([1, 2, 3])

In [8]:
my_mat = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
np.arange(2, 101, 2).reshape(5, 10)

array([[  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [ 22,  24,  26,  28,  30,  32,  34,  36,  38,  40],
       [ 42,  44,  46,  48,  50,  52,  54,  56,  58,  60],
       [ 62,  64,  66,  68,  70,  72,  74,  76,  78,  80],
       [ 82,  84,  86,  88,  90,  92,  94,  96,  98, 100]])

In [19]:
np.zeros((5, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [21]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [22]:
np.ones((5, 10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [31]:
np.linspace(1, 20, 15).ravel()

array([ 1.        ,  2.35714286,  3.71428571,  5.07142857,  6.42857143,
        7.78571429,  9.14285714, 10.5       , 11.85714286, 13.21428571,
       14.57142857, 15.92857143, 17.28571429, 18.64285714, 20.        ])

In [33]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [35]:
np.random.rand(4, 5)            # uniform distribution of random numbers between 0 and 1

array([[0.3023783 , 0.48699311, 0.5605224 , 0.32178594, 0.22400672],
       [0.67613916, 0.92327937, 0.37678666, 0.27403175, 0.76207082],
       [0.81611553, 0.41726637, 0.49280409, 0.23611942, 0.2845978 ],
       [0.12694842, 0.73950094, 0.81674312, 0.34083807, 0.25903795]])

In [36]:
np.random.randn(3, 4)           # uniform standard distribution (mean=0; standard_deviation=1)

array([[ 1.2201509 ,  0.56748596,  0.23778236, -0.92542664],
       [-0.08305633, -1.87402353,  0.89927294,  1.64929177],
       [ 0.70637453,  1.39460292,  0.56014465, -0.4182429 ]])

In [37]:
np.random.randint(-100, 100, 10)

array([-73, -65,  22,  33, -47,  -7,   2,  85, -72,  74])

In [38]:
arr = np.arange(25)

In [39]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [40]:
ranarr = np.random.randint(0, 50, 10)

In [41]:
ranarr

array([ 1,  4,  2,  4, 46,  4, 25,  6, 14, 10])

In [42]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [43]:
arr.dtype

dtype('int32')